Repository drashland/drash, pull requests merged in 2020-11, with the labels that each got.

#421 feat: compile time middleware
  src/http/server.ts
  src/interfaces/server_configs.ts
  src/interfaces/server_middleware.ts
  tests/integration/app_3000_resources/returning_invalid_response_in_resource_test.ts
  tests/integration/app_3003_middleware/compile_time_middleware_resource_test.ts
  tests/integration/app_3003_middleware/middleware/compile_time_middleware.ts
  tests/integration/app_3003_middleware/resources/compile_time_middleware_resource.ts
  tests/unit/http/middleware_test.ts
Labels: Type: Minor

#428 feat: after_resource middleware hook
  src/http/response.ts
  src/http/server.ts
  src/interfaces/server_middleware.ts
  tests/integration/app_3000_resources/browser_request_resource_test.ts
  tests/integration/app_3003_middleware/after_resource_middleware_resource_test.ts
  tests/integration/app_3003_middleware/compile_time_middleware_resource_test.ts
  tests/integration/app_3003_middleware/middleware/after_resource_middleware.ts
  tests/integration/app_3003_middleware/middleware/compile_time_middleware.ts
  tests/integration/app_3003_middleware/resources/after_resource_middleware_resource.ts
  tests/unit/http/middleware_test.ts
Labels: Type: Minor

#404 feat: Add getAll methods for header, body and path params
  src/http/request.ts
  tests/unit/http/request_test.ts
Labels: Remark: Approved, Type: Minor

#424 deprecate: Drash.Compilers.TemplateEngine
  deps.ts
  mod.ts
  src/compilers/template_engine.ts
  src/http/response.ts
  tests/integration/app_3001_views/resources/template_engine_null_data_resource.ts
  tests/integration/app_3001_views/resources/template_engine_resource.ts
  tests/integration/app_3001_views/template_engine_null_data_resource_test.ts
  tests/integration/app_3001_views/template_engine_resource_test.ts
  tests/unit/mod_test.ts
Labels: Type: Minor

#393 chore: make resource lookup faster
  .github/workflows/master.yml
  console/benchmark_app.ts
  deps.ts
  mod.ts
  src/exceptions/invalid_path_exception.ts
  src/http/server.ts
  tests/integration/app_3000_resources/coffee_resource_test.ts
  tests/integration/app_3000_resources/request_accepts_resource_test.ts
  tests/unit/http/server_test.ts
Labels: Type: Patch

#436 fix: create app script not building apps correctly
  README.md
  console/create_app/app_api.ts
  console/create_app/app_web_app.ts
  console/create_app/public/css/index.css
  console/create_app/public/views/index.html
  console/create_app/react/app.tsx
  console/create_app/resources/home_resource_api.ts
  console/create_app/resources/home_resource_web_app.ts
  console/create_app/server_api.ts
  console/create_app/server_web_app.ts
  console/create_app/tests/resources/home_resource_test.ts
  console/create_app/tests/resources/home_resource_test_api.ts
  console/create_app/tests/resources/home_resource_test_web_app.ts
  console/create_app/vue/app.vue
  create_app.ts
  src/compilers/template_engine.ts
  src/http/server.ts
  tests/cli/create_app_test_http.ts
  tests/cli/create_app_test_local.ts
Labels: Type: Patch

#440 fix: Fix publishing to nest.land
  .github/workflows/release.yml
  egg.json
Labels: Type: Patch

#444 chore: Move website event from release to pre-release
  .github/workflows/pre_release.yml
  .github/workflows/release.yml
  console/bumper_ci_service.ts
  console/bumper_ci_service_files.ts
Labels: Remark: Approved, Type: Chore

#445 Refactor create app
  tests/cli/create_app_test_http.ts
  tests/cli/create_app_test_local.ts
  tests/deps.ts
Labels: Type: Chore

#455 chore: Remove bloat
  .github/workflows/master.yml
  README.md
  console/bumper_ci_service.ts
  console/bumper_ci_service_files.ts
Labels: Type: Chore

#456 chore: Refactor create app tests again
  .github/workflows/master.yml
  tests/cli/create_app_test_http.ts
  tests/cli/create_app_test_local.ts
  tests/cli/test_methods.ts
  tests/unit/core_loggers/file_logger_test.ts
  tmp/.gitkeep
Labels: Type: Chore
