Repository drashland/drash, pull requests merged in 2020-10, with the labels that each got.

#386 fix: Dont return null if body param is false; Support body params being data types other than a string
  src/http/request.ts
  tests/integration/app_3000_resources/resources/coffee_resource.ts
  tests/unit/http/request_test.ts
Labels: patch

#392 chore: Send request to website on release to update versions
  .github/workflows/release.yml
Labels: chore

#401 fix: Content length was 2 when content type is JSON and body is empty
  src/http/response.ts
Labels: patch

#396 feat: Add getAllUrlQueryParams method
  .github/workflows/master.yml
  src/http/request.ts
  tests/cli/create_app_test_http.ts
  tests/unit/http/request_test.ts
  tsconfig.json
Labels: hacktoberfest-accepted, minor

#412 feat: Throw an error if response is not correctly returned from resource
  src/http/server.ts
  tests/integration/app_3000_resources/resources/returning_invalid_response_in_resource.ts
  tests/integration/app_3000_resources/returning_invalid_response_in_resource_test.ts
  tests/integration/app_3000_resources/tests.ts
  tests/unit/http/server_test.ts
Labels: minor

#377 feat: Add -with-react flag to create app
  console/create_app/package_react.json
  console/create_app/public/views/index_react.html
  console/create_app/react/app.tsx
  console/create_app/tsconfig_react.json
  console/create_app/webpack_react.config.js
  create_app.ts
  tests/cli/create_app_test_local.ts
Labels: minor

#410 chore: Fix http create app tests for forks
  .github/workflows/master.yml
  tests/cli/create_app_test_http.ts
Labels: chore, patch

#406 feat: virtual paths
  mod.ts
  src/exceptions/configs_exception.ts
  src/http/server.ts
  src/interfaces/server_configs.ts
  tests/integration/app_3001_views/template_engine_null_data_resource_test.ts
  tests/integration/app_3001_views/template_engine_resource_test.ts
  tests/integration/app_3001_views/view_resource_test.ts
  tests/unit/http/middleware_test.ts
  tests/unit/http/server_test.ts
Labels: minor

#416 chore: fix http create app tests
  tests/cli/create_app_test_http.ts
Labels: patch

#420 fix: optional args regex not matching non-alphanumeric characters
  src/http/server.ts
  tests/integration/app_3000_resources/optional_path_params_test.ts
  tests/integration/app_3000_resources/resources/optional_path_params_resource.ts
Labels: patch

#415 chore: Automate tweets and reddit on release
  .github/workflows/release.yml
Labels: chore

#380 chore: Add pre release workflow
  .github/workflows/bumper.yml
  .github/workflows/pre_release.yml
  console/bumper_ci_service.ts
  console/bumper_ci_service_files.ts
  console/update_deno_version_strings.ts
  deps.ts
  mod.ts
  tests/data/pattern_types.txt
  tests/unit/console/bumper_ci_service_test.ts
Labels: chore, patch

#422 chore: Include usage of react with create app section
  README.md
Labels: chore
