Repository drashland/drash, pull requests merged in 2022-05, with the labels that each got.

#625 fix: change service.end() to be request.end()
  src/http/request.ts
  src/http/server.ts
  src/http/service.ts
  src/interfaces.ts
  tests/integration/service_ends_lifecycle_test.ts
  tests/unit/http/service_test.ts
Labels: Type: Patch

#637 perf: don't find resource if already matched to previous request URL
  src/http/server.ts
Labels: Type: Patch

#638 fix: check for non-empty accept header before performing accept header flow
  src/http/server.ts
Labels: Type: Patch

#633 chore: Update docblocks
  src/http/request.ts
  src/http/response.ts
  src/http/server.ts
Labels: Type: Chore

#645 chore: update services' deps
  console/deps.ts
  src/services/csrf/deps.ts
  src/services/etag/deps.ts
  src/services/graphql/deps.ts
Labels: Type: Chore

#634 fix: ensure consistent falsy return values for body params
  src/http/request.ts
  tests/unit/http/request_test.ts
Labels: Type: Patch

#649 feat(http/request): allow access to the original request
  src/http/request.ts
  tests/unit/http/request_test.ts
Labels: Type: Minor

#647 feat: remove GraphQL service empty resource requirement; add option to change playground endpoint
  src/services/graphql/deps.ts
  src/services/graphql/graphql.ts
  src/services/graphql/graphql_resource.ts
  tests/integration/graphql_test.ts
Labels: Type: Minor
